### ISSUE TITLE
missile + champion

### ISSUE THREAD

**Issue by morteeke** [brittonhayes/aos#3]
Hey @brittonhayes, me again.

I was looking inside units.yaml to add some units but it appears that it's missing the 'Champion' explanation and 'Missile Weapons'. Except if I am looking over it ofcourse.

Thanks for you time!

**Comment by brittonhayes** [comment]
Well hello again! I can totally add the champion field. That's no problem.

For the weapons, I opted to do an array of objects where all the weapons (missile and melee) are under the weapons array. 

So, two options:

1. I separate the weapons into `missile_weapons` and `melee_weapons` arrays
2. I add the field `weapon_type` to each Weapon object in the `weapons` array. Then add `melee` or `missile` into that field for each.

Do you have a preference on one over the other?

**Comment by morteeke** [comment]
I think I would prefer option 1 but both will definitly work.

Great work so far by the way!

Edit: Do I just commit the data I wrote or do I need to fork or something?

**Comment by brittonhayes** [comment]
I'll have to update the model in the API spec since we're changing the object's fields and run `task gen` to re-generate the `warhammer.gen.go` code. And I'll have to migrate the existing `units.yaml` entries to follow the new format. Then you'll be free to add your data to the fixtures file via a fork + pull request. 😄

If you were just adding data, you'd just have to do fork + PR, it's just because we're updating the API spec and models themselves, it's a couple more steps.

I can get all that stuff going in about 30min once I wrap with work for the day.

**Comment by brittonhayes** [comment]
Hey again @morteeke! I've added `missile_weapons` and `melee_weapons` to the models and API spec so feel free to try them out or add some data to the fixtures! 

I wasn't totally sure if I understood your champions feature request so I left that out of this release temporarily. Where can I find more information about "champion explanation"?

**Comment by morteeke** [comment]
Hey @brittonhayes, looks perfect! 

With champion I mean the regulation about having 1 model in the unit as a champion. That model gets for example an extra attack. 


![ani](https://github.com/brittonhayes/warhammer/assets/87078342/51e32e0d-c1db-439e-88d0-9939cef67a30)

**Comment by brittonhayes** [comment]
Ohhhh now I get what ya mean. Okay I'll take a look at adding support for this when I get home tonight!
